### ISSUE TITLE
imou integration not showing up in Home Assist evern after download - restart - teice - still no imou..

### ISSUE THREAD

**Issue by scargill** [user2684/imou_life#108]
## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by voicoi0401** [comment]
imou lite failed to set up

**Comment by frankiesoc** [comment]
Same here.
ERROR (MainThread) [imouapi] Too many unsuccesful connection attempts

**Comment by grisu112** [comment]
Same here, integration no longer working.

**Comment by user2684** [comment]
Hi, guys, I cannot find the way to reproduce this one...I have HA 2024.5.3 and the latest version of the Imou integration. I guess you have already checked if reached the API usage limite right? (https://github.com/user2684/imou_life/wiki/Imou-API-usage-restrictions) Thanks

**Comment by rpolverini** [comment]
Hey @user2684 I updated HA and is my first time with your integration (I never seen working on my HA)
I make new API credentials for my cam, and is my first Imou cam too, then all the limits are cleared.
![image](https://github.com/user2684/imou_life/assets/6001067/fbf93dc4-b97a-45a2-89ca-379743d70636)

Updated all to these lasts versions today:
Core   2024.6.3
Supervisor  2024.06.0
Operating System   12.4
Frontend    20240610.1

I can see all ok from Imou android app.

I can see thumbnails...
![image](https://github.com/user2684/imou_life/assets/6001067/00f1ef8e-7e66-4983-b285-868560757095)


But I am having this error when try to add the cam to dashboard and play:
---------------------------------------------
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 12:24:05 PM (2 occurrences)
Last logged: 12:24:17 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/imouapi/device_entity.py", line 598, in async_get_image
    raise InvalidResponse(f"status code {response.status}")
imouapi.exceptions.InvalidResponse: status code 404

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 815, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 833, in handle
    image = await _async_get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 187, in _async_get_image
    else await camera.async_camera_image(width=width, height=height)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/imou_life/camera.py", line 98, in async_camera_image
    return await self.sensor_instance.async_get_image()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/imouapi/device_entity.py", line 601, in async_get_image
    raise InvalidResponse(f"unable to retrieve image from {url}: {exception}") from exception
imouapi.exceptions.InvalidResponse: unable to retrieve image from https://ali-pano-fk.oss-eu-central-1.aliyuncs.com/snappic/9G0D001PBVB8D1D_img/Alarm/0/f11536a5ab864583ae6be752560fb43a.jpg?Expires=1719415497&OSSAccessKeyId=LTAIyrmtqw10bcyQ&Signature=Pt8%2FKpsl%2BV%2F6njOZWxEdMkoCQYA%3D: status code 404
---------------------------------------------

Please tell me if I can help in the resolution, new in integrations, never touched code there :D but happy to learn!

**Comment by user2684** [comment]
Hi @rpolverini, can you try if any of the suggestions from https://github.com/user2684/imou_life/issues/105 works for you? Thanks

**Comment by rpolverini** [comment]
![image](https://github.com/user2684/imou_life/assets/6001067/7bb38d39-7b55-42c3-9828-f38e26d80ecc)
Hey! this does not work, i tested with 30 and 50 secs.
Enabling the SD works (I dont tested before)
Thanks! 
The cammera is far from the WiFi network, then make sense use SD instead HD!!

**Comment by user2684** [comment]
Added to https://github.com/user2684/imou_life/wiki/Known-Issues
