### ISSUE TITLE
Snapshot preview no longer displayed

### ISSUE THREAD

**Issue by GGSSDD** [user2684/imou_life#127]
Hi, 
Since last night the snapshot previews for the cameras are no longer being displayed. Any idea what's causing this?

Thank you!

## Version of the custom_component
1.0.15

## Debug log

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
First occurred: 08:18:55 (953 occurrences)
Last logged: 10:31:44

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/imouapi/device_entity.py", line 598, in async_get_image
    raise InvalidResponse(f"status code {response.status}")
imouapi.exceptions.InvalidResponse: status code 404

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 985, in get
    return await self.handle(request, camera)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 1003, in handle
    image = await _async_get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 217, in _async_get_image
    else await camera.async_camera_image(width=width, height=height)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/imou_life/camera.py", line 98, in async_camera_image
    return await self.sensor_instance.async_get_image()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/imouapi/device_entity.py", line 601, in async_get_image
    raise InvalidResponse(f"unable to retrieve image from {url}: {exception}") from exception
imouapi.exceptions.InvalidResponse: unable to retrieve image from https://ali-pano-fk.oss-eu-central-1.aliyuncs.com/snappic/7F01E97PAZ6657C_img/Alarm/0/43091980fdd84ed4af035c5fa33003cb.jpg?Expires=1733984333&OSSAccessKeyId=LTAIyrmtqw10bcyQ&Signature=fHk7n8ytKY8f8bTJ5RH7beTBawg%3D: status code 404
```

**Comment by h3ld3rkid** [comment]
Same where

**Comment by andyreload** [comment]
Any fix ?

**Comment by remcovdb79** [comment]
Yeah same here. HACS integration is up and running, but no image displaying anymore

**Comment by h3ld3rkid** [comment]
Add funds , 1 dollar for exmpl and will be solved

**Comment by remcovdb79** [comment]
Adding funds is not helping. Already did that. Stopped using the integration

**Comment by h3ld3rkid** [comment]
> Adding funds is not helping. Already did that. Stopped using the integration

You use what else?
I add funds and helps..

**Comment by remcovdb79** [comment]
I added 5 dollar on top of the 1 dollar that was still there and the money was gone in a few days, don't know why cause I disabled all notifications for months already since the money was running out too fast. 

I now use the ONVIF integration, then you still have about 9 entities to use per cam, enough for me and works just fine.

**Comment by GGSSDD** [comment]
> I added 5 dollar on top of the 1 dollar that was still there and the money was gone in a few days, don't know why cause I disabled all notifications for months already since the money was running out too fast.
> 
> I now use the ONVIF integration, then you still have about 9 entities to use per cam, enough for me and works just fine.

I don’t know what you’re doing with your cameras, but it seems you’re doing something wrong. I have 3 cameras which use roughly 17000 API requests per day with a cost of only 0.03$. That’s about 11$/year, which i not much considering the fact that this integration gives you a lot of options, that other integrations don’t.

**Comment by user2684** [comment]
Hi, regarding the snapshot preview, I'd recommend to use the ONVIF integration which is way more reliable them getting the image through the Imou API. The 404 error is due to the fact that when the integration needs a preview, calls the api, then wait for a few seconds waiting for the image to be ready and download the image. So sometimes the image is ready after a long time (which can be mitigated setting a higher timeout in the integration settings), sometimes the image is never generated by the server so nothing we can do. 

Regarding the status of this integration, I have recently decided to stop actively developing it or at least adding new features. For more information, have a look at https://github.com/user2684/imou_life/wiki/Status-of-the-integration

**Comment by remcovdb79** [comment]
Thanks for your reply. Currently I am using ONVIF and that works ok,
although the preview for a couple of my cams (Imou Cruiser 2 3K) giving me
mainly green gibberish shit in my dashboard...any idea how to make that
better?

Op vr 6 jun 2025 om 14:51 schreef user2684 ***@***.***>:

**Comment by remcovdb79** [comment]
Like this; [image: image.png]

Op vr 6 jun 2025 om 15:10 schreef Remco van den Bergh <
***@***.***>:
