### ISSUE TITLE
No video from Camera Ranger 2 C

### ISSUE THREAD

**Issue by Nicosdem31** [user2684/imou_life#130]
Integration for Imou Ranger 2C is failing and not giving any video livre stream 

    _LOGGER.warning(msg, stack_info=True)
2024-12-20 14:38:29.911 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] Adding Camera (HD)
2024-12-20 14:38:29.911 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] Adding Camera (SD)
2024-12-20 14:38:29.911 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] requested camera stream url
2024-12-20 14:38:30.051 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Callback url added to HA
2024-12-20 14:38:30.067 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Motion Alarm added to HA
2024-12-20 14:38:30.080 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.camera_bureau_camera for domain camera with platform imou_life
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 829, in async_internal_added_to_hass
    await self.async_refresh_providers(write_state=False)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 847, in async_refresh_providers
    new_provider = await self._async_get_supported_webrtc_provider(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        async_get_supported_provider
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 871, in _async_get_supported_webrtc_provider
    return await fn(self.hass, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/camera/webrtc.py", line 373, in async_get_supported_provider
    if not providers or not (stream_source := await camera.stream_source()):
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/imou_life/camera.py", line 106, in stream_source
    return await self.sensor_instance.async_get_stream_url()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/imouapi/device_entity.py", line 690, in async_get_stream_url
    raise APIError(f"unable to get live streaming, url not found in {existing_stream}")
imouapi.exceptions.APIError: unable to get live streaming, url not found in {'url': None, 'token': None}
2024-12-20 14:38:30.082 DEBUG (MainThread) [custom_components.imou_life] [Camera Bureau] requested camera stream url
2024-12-20 14:38:30.097 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Status added to HA
2024-12-20 14:38:30.100 DEBUG (MainThread) [custom_components.imou_life] Camera Bureau Status indicator added to HA
2024-12-20 14:38:30.192 ERROR (MainThread) [homeassistant.components.camera] Error adding entity camera.camera_bureau_camerasd for domain camera with platform imou_life
Traceback (most recent call last):

**Comment by letienne** [comment]
similar issue with the cell 3c camera:

raise APIError(f"unable to get live streaming, url not found in {existing_stream}")
imouapi.exceptions.APIError: unable to get live streaming, url not found in {'url': None, 'token': None}

**Comment by 50Drg** [comment]
i have the same issue, someone found the issue why it`s not working the stream ?

**Comment by cataldie** [comment]
Me too, did anyone find a solution?

**Comment by fracrm** [comment]
Me too, I have the same problem, I have 6 camera of same model: 5 camera have problem (no streaming) and 1 without problem..

**Comment by elenaomfg** [comment]
Same problem here… does anyone find any solution?

**Comment by colibri17** [comment]
Same problem here with model Ranger 2C. Any help?

**Comment by Meo68** [comment]
Idem, no video stream on my Ranger 2C... Help please!

**Comment by ipa64** [comment]
Same for me 4 imou camera no one is working.

**Comment by user2684** [comment]
Hi, this is likely due to an unsupported model/functionality. Unfortunately some models use publicly documented APIs, others don't or mix the two. Unfortuantely not something I can fix, also have a look here: https://github.com/user2684/imou_life/wiki/Status-of-the-integration
