### ISSUE TITLE
Malformed or unexpected API response when adding light bulb

### ISSUE THREAD

**Issue by ramonibz** [user2684/imou_life#50]
## Version of the custom_component
1.0.12

## Configuration
Configured using HACS

## Describe the bug
I've installed the imou integration using HACS and when I try to add a device (an imou bulb), after entering the appId and the appSecret, if I check "discover registered devices" when I click send button I get the error "Malformed or unexpected API response". If I don't check the "discover registered devices" I go to the next screen where I set the device id and a name and when clicking send I get the same error  "Malformed or unexpected API response".

## Debug log

Following is the error log I found (I substitute the real device id by XXX)

```text

InvalidResponse: missing parameter or error parsing in {'expandChanNum': '', 'productId': '5w244i7j0d2l6h37', 'trackFollowStatus': '', 'httpPort': '80', 'privatePort': '', 'rtspPort': '554', 'deviceId': 'XXX', 'version': 'V1.000.0000002.0.R', 'aplist': [], 'accessType': 'PaaS', 'p2pPort': '554', 'port': '37777', 'encryptMode': 0, 'tlsPrivatePort': '37778', 'name': 'Luz escalera abajo', 'deviceModel': 'CL1B-5-E27', 'ability': '', 'brand': 'easy4Ip', 'playToken': 'svaDSjtNAJnO+P6d4vLGhwr07nvJOzQtTqs7JELzSw6wEOFKm+uTbci0eO8dBLwfM47gV5pumwf+id4irBcBLvq4HOZt1BxLrQ3BpGbZ0Vfpo7UVxjMfYU4Oene/7dVbzACMSZvX8naOdWe3RybYLbq8iNuGtWNI7Q/KZXj8HrOAMCya8V9Af8KZ5yJkEpCB', 'shareStatus': 'owner', 'status': 'online'} Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/imouapi/device.py", line 189, in async_initialize self._catalog = device_data["catalog"] KeyError: 'catalog' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/imou_life/config_flow.py", line 130, in async_step_discover await self._discover_service.async_discover_devices() File "/usr/local/lib/python3.10/site-packages/imouapi/device.py", line 633, in async_discover_devices await device.async_initialize() File "/usr/local/lib/python3.10/site-packages/imouapi/device.py", line 352, in async_initialize raise InvalidResponse(f" missing parameter or error parsing in {device_data}") from exception imouapi.exceptions.InvalidResponse: missing parameter or error parsing in {'expandChanNum': '', 'productId': '5w244i7j0d2l6h37', 'trackFollowStatus': '', 'httpPort': '80', 'privatePort': '', 'rtspPort': '554', 'deviceId': 'AMWTLBC23981522', 'version': 'V1.000.0000002.0.R', 'aplist': [], 'accessType': 'PaaS', 'p2pPort': '554', 'port': '37777', 'encryptMode': 0, 'tlsPrivatePort': '37778', 'name': 'Luz escalera abajo', 'deviceModel': 'CL1B-5-E27', 'ability': '', 'brand': 'easy4Ip', 'playToken': 'svaDSjtNAJnO+P6d4vLGhwr07nvJOzQtTqs7JELzSw6wEOFKm+uTbci0eO8dBLwfM47gV5pumwf+id4irBcBLvq4HOZt1BxLrQ3BpGbZ0Vfpo7UVxjMfYU4Oene/7dVbzACMSZvX8naOdWe3RybYLbq8iNuGtWNI7Q/KZXj8HrOAMCya8V9Af8KZ5yJkEpCB', 'shareStatus': 'owner', 'status': 'online'}

```

**Comment by user2684** [comment]
Similar or the same with#47. Looks like the light bulb is exposing a completely different set of API which of course is not documented apparently :-/ I'd say not supported right now, will look into it in the future. If you findany information regarding these APIs anywhere let me know which would help :-)

**Comment by user2684** [comment]
Keeping track of this enhancement into the more generic #52, closing this for now.
