### ISSUE TITLE
Adding support for the new Imour Ranger RC

### ISSUE THREAD

**Issue by MiAutomations** [user2684/imou_life#58]
## Describe the bug

I try to added the new IMOU Ranger RC, the device appears in the HA - Home Assistant, but I can't load the image stream or use some of the sensors and the buttons as you can see in the imagens bellow 

![image](https://user-images.githubusercontent.com/47602733/228486856-c02a9170-8ea3-434f-8498-b3701a836599.png)
![image](https://user-images.githubusercontent.com/47602733/228486899-d9b1334e-4b35-4971-9f2d-d393e4699a12.png)
![image](https://user-images.githubusercontent.com/47602733/228486939-ed514b30-bb55-4fee-89bc-3453362c4650.png)

## Debug log

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/imou_life/camera.py:98
Integration: Imou Life (documentation, issues)
First occurred: 10:05:01 AM (4 occurrences)
Last logged: 10:05:30 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 234, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 724, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 742, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 170, in _async_get_image
    if image_bytes := await camera.async_camera_image(
  File "/config/custom_components/imou_life/camera.py", line 98, in async_camera_image
    return await self.sensor_instance.async_get_image()
  File "/usr/local/lib/python3.10/site-packages/imouapi/device_entity.py", line 562, in async_get_image
    data = await self.api_client.async_api_setDeviceSnapEnhanced(self._device_id)
  File "/usr/local/lib/python3.10/site-packages/imouapi/api.py", line 540, in async_api_setDeviceSnapEnhanced
    return await self._async_call_api(api, payload)
  File "/usr/local/lib/python3.10/site-packages/imouapi/api.py", line 216, in _async_call_api
    raise APIError(error_message)
imouapi.exceptions.APIError: DV1007: Device offline
```

Can you please add the support for this Device ? 

Thank you for your support and best regards

**Comment by user2684** [comment]
Hi, there are some operations not allowed by the Imou API when a device is offline. At least this is what the Imou server is saying, that the device is offline :-) Is it the case? When the device comes online you should get a different behavior

**Comment by MiAutomations** [comment]
Hello The device is online and I can Access to the same using the APP Imou 

![Screenshot_2023-04-04-10-24-54-579_com mm android smartlifeiot](https://user-images.githubusercontent.com/47602733/229749440-9414ebd1-cc5f-44df-8f9e-25ad60750021.jpg)


Regarding the Access over this integration I still facing this issue That I reported 

Please let me know if you need any further information 

Thank you

**Comment by user2684** [comment]
super weird :-) That Device offline message comes directly from the Imou servers. Trivial check but can you please double check the device id is the same? I guess so. I might need you to run some python code to troubleshoot this, outside Home Assistant. Are you ok with that? If so I will share some instructions. Thanks

**Comment by user2684** [comment]
Thank you. Try the following in a python 3.9+ environment (outside HA):
1) install the dependencies
`pip3 install aiohttp asyncio imouapi`
2) Discover available devices, identify the one which is offline (provide your app id and app secret):
`python -m imouapi.cli --logging debug --app-id <app_id> --app-secret <app_secret> discover`
3) get details of the ranger RC camera by providing the device id:
`python -m imouapi.cli --logging debug --app-id <app_id> --app-secret <app_secret> get_device <device_id>`

Have a look at the output, if there is no sensitive data, feel free to share here for review. Otherwise search for anything strange with that device and if showing up as offline also with those commands. Thanks

**Comment by MiAutomations** [comment]
> Thank you. Try the following in a python 3.9+ environment (outside HA):
> 
> 1. install the dependencies
>    `pip3 install aiohttp asyncio imouapi`
> 2. Discover available devices, identify the one which is offline (provide your app id and app secret):
>    `python -m imouapi.cli --logging debug --app-id <app_id> --app-secret <app_secret> discover`
> 3. get details of the ranger RC camera by providing the device id:
>    `python -m imouapi.cli --logging debug --app-id <app_id> --app-secret <app_secret> get_device <device_id>`
> 
> Have a look at the output, if there is no sensitive data, feel free to share here for review. Otherwise search for anything strange with that device and if showing up as offline also with those commands. Thanks

Hello And thank you for your support 

I try to execute this outside of the HA environment as you suggested, And I'm trying to execute this in a windows machine 

Right now I'm facing this issue 

![image](https://user-images.githubusercontent.com/47602733/233656210-767a0e23-07dc-49b3-94ea-b5fe1c98f1de.png)

Can you please verify? Thank you

**Comment by user2684** [comment]
Thanks. On Windows you need to run the pip3 command *before* running python -m. Let me know. Thanks

**Comment by MiAutomations** [comment]
> 2\. -m imouapi.cli --logging debug --app-id <app_id> --app-secret <app_secret> discover

Hello 

I successfully running the first command and I also update de PIP3 following the instructions

But now trying to running the next command I'm receiving the following error msg including the PIP3  before the -m ass your indications 

```
python pip3 -m imouapi.cli --logging debug --app-id <app_id> --app-secret <app_secret> discover
```

![image](https://user-images.githubusercontent.com/47602733/234570665-c3e60d7c-55c4-4d1c-9276-9787baa6da2d.png)

Can you please help me in order to try share more info about this camera to you 

Thank you for your support and best regards

**Comment by user2684** [comment]
Hi, looks like you put your app id and app secret between brackets (e.g. `<app_id>`), try without (e.g. just `app_id`)

**Comment by user2684** [comment]
Closing due to inactivity
