### ISSUE TITLE
APIError: DV1026: The device does not support the call of this function.

### ISSUE THREAD

**Issue by Diegocampy** [user2684/imou_life#87]
All day this error with the integration and I don't able to solve it. 

.imou_life
Source: custom_components/imou_life/entity.py:81
Integration: Imou Life (documentation, issues)
First occurred: 11:54:01 (2 occurrences)
Last logged: 11:54:03

APIError: DV1026: The device does not support the call of this function. Traceback (most recent call last): File "/config/custom_components/imou_life/entity.py", line 79, in async_added_to_hass await self.sensor_instance.async_update() File "/usr/local/lib/python3.11/site-packages/imouapi/device_entity.py", line 294, in async_update data = await self.api_client.async_api_getDeviceCameraStatus(self._device_id, self._name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 355, in async_api_getDeviceCameraStatus return await self._async_call_api(api, payload) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/imouapi/api.py", line 227, in _async_call_api raise APIError(error_message) imouapi.exceptions.APIError: DV1026: The device does not support the call of this function.

**Comment by Diegocampy** [comment]
Duplicated issue bug
